apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: sample-pipeline-run-sk041
  namespace: class-2
spec:
  pipelineRef:
    name: sample-pipeline
  params:
    - name: app-name
      value: my-app
