apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: read-file-task-sk041
  namespace: class-2
spec:
  workspaces:
    - name: shared-data
  steps:
    - name: read-file
      image: alpine:3.20
      script: |
        #!/bin/sh
        echo "Reading file..."
        cat $(workspaces.shared-data.path)/message.txt
