apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: simple-test-pipeline-run-sk041
  namespace: class-2
spec:
  pipelineRef:
    name: simple-test-pipeline
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: tekton-demo-pvc
